[package]
name = "bulletproofs"
version = "0.1.0"
edition = "2021"

[dependencies]
bulletproofs = "5.0.0"
curve25519-dalek = "4.0"
rand = "0.8"
merlin = "3.0"

[[bin]]
name = "rangeproof"
path = "src/rangeproof.rs"