version: '3'

services:
  gitbook:
    image: fellah/gitbook:latest
    container_name: gitbook
    ports:
      - "4000:4000"  
    volumes:
      - ./book:/srv/gitbook  
    command: "gitbook serve"  
    restart: unless-stopped